package web

var panelTranslations = map[string]map[string]string{
	"he": {
		"main": "ראשי", "engagement": "מעורבות", "bot_settings": "הגדרות הבוט", "system_settings": "הגדרות מערכת", "sign_out": "יציאה", "development_mode": "מצב פיתוח", "local_access": "גישה מקומית",
		"sign_in": "התחברות", "welcome_back": "ברוכים השבים", "login_copy": "התחברו כדי לנהל תורים, לקוחות ואת הידע של העוזרת.", "panel_password": "סיסמת לוח הבקרה", "open_dashboard": "פתיחת לוח הבקרה",
		"control_center": "מרכז ניהול העסק", "schedule": "יומן", "assistant_online": "העוזרת מחוברת", "upcoming": "קרובים", "appointments": "תורים", "customers": "לקוחות", "known_contacts": "אנשי קשר", "today": "היום", "messages": "הודעות", "ai_activity": "פעילות AI", "calls_today": "קריאות היום", "master_calendar": "יומן ראשי", "owner_time": "זמן בעלת העסק", "confirmed": "מאושר", "completed": "הושלם", "selected_appointment": "תור נבחר", "date": "תאריך", "time": "שעה", "status": "סטטוס", "save_changes": "שמירת שינויים", "customer_directory": "רשימת לקוחות", "messages_count": "הודעות", "subscribed": "רשום", "declined": "הוסר", "not_subscribed": "לא רשום", "no_customer_activity": "עדיין אין פעילות לקוחות.",
		"bot_configuration": "הגדרות הבוט", "assistant_settings": "הגדרות העוזרת", "assistant_settings_copy": "ידע עסקי, כללי פעולה ונכסים שנשלחים ללקוחות.", "business_profile": "פרופיל העסק", "knowledge_policy": "ידע ומדיניות", "source_of_truth": "שדות אלה הם מקור המידע של העוזרת.", "save_bot_settings": "שמירת הגדרות הבוט", "customer_media": "מדיה ללקוחות", "visual_assets": "נכסים חזותיים",
		"settings_guide": "איך ההגדרות עובדות", "bot_guide_copy": "העוזרת מסתמכת על המידע בדף זה. מחירים ומשכים צריכים להשתמש באותם שמות שירות. הוראות העוזרת קובעות סגנון וכללי עסק, אך אינן עוקפות אבטחה או בדיקות תורים.", "system_guide_copy": "מזהים וכתובות מוצגים לעריכה; סודות קיימים אינם מוצגים. שדה סוד ריק שומר את הערך הקיים. לאחר שינוי חיבור יש להפעיל מחדש את הקונטיינרים ולבדוק את האבחון.",
		"business_name": "שם העסק", "business_type": "סוג העסק", "admin_phone": "מספר WhatsApp של המנהל", "business_hours": "שעות פעילות", "owner_handoff": "העברה לבעלת העסק", "owner_phone": "מספר WhatsApp של בעלת העסק", "share_owner": "שתפי את מספר בעלת העסק עם לקוחות שמבקשים", "notify_owner": "הודיעי לבעלת העסק גם כשהמספר נמסר", "pricing": "מחירים ללקוחות", "service_durations": "משך טיפולים", "products_services": "מוצרים ושירותים", "additional_info": "מידע נוסף על העסק", "ask_only": "למסור רק כשנשאלים במפורש", "assistant_instructions": "הוראות לעוזרת", "daily_ai": "תשובות AI יומיות", "default_appointment": "משך תור ברירת מחדל", "reminder_hours": "שעות לפני תזכורת", "admin_notice": "דקות לפני הודעת מנהל", "asset_name": "שם הנכס", "when_to_use": "מתי להשתמש", "image_file": "קובץ תמונה", "upload_asset": "העלאת נכס", "delete": "מחיקה",
		"system_configuration": "הגדרות מערכת", "integrations": "חיבורים וסביבת עבודה", "integrations_copy": "הגדרות WhatsApp, OpenRouter ו-Cloudflare. סודות קיימים לעולם אינם מוצגים.", "panel_preferences": "העדפות לוח הבקרה", "appearance": "מראה", "language": "שפה", "light": "בהיר", "dark": "כהה", "english": "אנגלית", "hebrew": "עברית", "whatsapp_cloud": "WhatsApp Cloud API", "openrouter": "OpenRouter", "cloudflare": "Cloudflare", "keep_secret": "השאירו ריק כדי לשמור את הסוד הקיים", "restart_required": "שינויי חיבור נשמרים בקובץ הסביבה ויחולו לאחר הפעלה מחדש של הקונטיינרים.", "save_system_settings": "שמירת הגדרות מערכת", "configured": "מוגדר", "not_configured": "לא מוגדר",
		"customer_engagement": "מעורבות לקוחות", "ask_learn_reward": "לשאול, ללמוד ולתגמל", "new_poll": "סקר חדש", "new_questionnaire": "שאלון חדש", "lottery": "הגרלה", "campaign_history": "היסטוריית קמפיינים", "results": "תוצאות",
		"onboarding_welcome": "ברוכים הבאים ל-OpenReception", "onboarding_welcome_copy": "ארבעה מסכים קצרים יסבירו איך להפעיל את המזכירה, לנהל את העסק ולחבר את השירותים.", "onboarding_dashboard": "היומן והלקוחות", "onboarding_dashboard_copy": "המסך הראשי מציג את היומן, התורים הקרובים, פעילות ההודעות ורשימת הלקוחות. לחצו על תור כדי להזיז אותו או לשנות סטטוס.", "onboarding_bot": "הגדרות הבוט", "onboarding_bot_copy": "כאן מגדירים את שם וסוג העסק, שירותים, מחירים, משכי טיפול, שעות, מדיניות, תזכורות ונכסים חזותיים. זהו מקור האמת של העוזרת.", "onboarding_system": "הגדרות מערכת", "onboarding_system_copy": "כאן מחברים WhatsApp Cloud API,‏ OpenRouter ו-Cloudflare, בוחרים מודל ושפה ומריצים בדיקות תקינות. סודות קיימים אינם מוצגים מחדש.", "onboarding_admin": "ניהול דרך WhatsApp", "onboarding_admin_copy": "מספר המנהל מתנהג כלקוח רגיל עד שליחת Admin. לאחר הזנת PIN אפשר לנהל תורים, הגדרות בוט, לקוחות וקמפיינים בשפה טבעית למשך שעה.", "skip_tutorial": "דילוג", "previous": "הקודם", "next": "הבא", "configure_bot": "הגדרת העסק", "configure_system": "חיבור שירותים",
	},
}

func translatePanel(language, key string) string {
	if language == "he" {
		if value := panelTranslations["he"][key]; value != "" {
			return value
		}
	}
	english := map[string]string{
		"main": "Main", "engagement": "Engagement", "bot_settings": "Bot settings", "system_settings": "System settings", "sign_out": "Sign out", "development_mode": "Development mode", "local_access": "Local access",
		"sign_in": "Sign in", "welcome_back": "Welcome back", "login_copy": "Sign in to manage appointments, customers and assistant knowledge.", "panel_password": "Control panel password", "open_dashboard": "Open dashboard",
		"control_center": "Business control center", "schedule": "Schedule", "assistant_online": "Assistant online", "upcoming": "Upcoming", "appointments": "appointments", "customers": "Customers", "known_contacts": "known contacts", "today": "Today", "messages": "messages", "ai_activity": "AI activity", "calls_today": "calls today", "master_calendar": "Master calendar", "owner_time": "Owner time", "confirmed": "Confirmed", "completed": "Completed", "selected_appointment": "Selected appointment", "date": "Date", "time": "Time", "status": "Status", "save_changes": "Save changes", "customer_directory": "Customer directory", "messages_count": "messages", "subscribed": "Subscribed", "declined": "Declined", "not_subscribed": "Not subscribed", "no_customer_activity": "No customer activity yet.",
		"bot_configuration": "Bot configuration", "assistant_settings": "Assistant settings", "assistant_settings_copy": "Business knowledge, operating rules and customer-facing assets.", "business_profile": "Business profile", "knowledge_policy": "Knowledge and policy", "source_of_truth": "These fields are the assistant’s source of truth.", "save_bot_settings": "Save bot settings", "customer_media": "Customer media", "visual_assets": "Visual assets",
		"settings_guide": "How settings work", "bot_guide_copy": "The assistant relies on this page as its source of truth. Prices and durations should use matching service names. Assistant instructions control tone and business policy but cannot bypass security or appointment validation.", "system_guide_copy": "Identifiers and URLs are shown for editing; existing secrets are never displayed. A blank secret field preserves its value. After changing an integration, restart the containers and run diagnostics.",
		"business_name": "Business name", "business_type": "Business type", "admin_phone": "Admin WhatsApp number", "business_hours": "Business hours", "owner_handoff": "Owner contact handoff", "owner_phone": "Owner WhatsApp number", "share_owner": "Share owner number with customers who ask", "notify_owner": "Also notify owner when the number is shared", "pricing": "Customer-visible pricing", "service_durations": "Service durations", "products_services": "Products and services", "additional_info": "Additional business information", "ask_only": "Only disclose when explicitly asked", "assistant_instructions": "Assistant instructions", "daily_ai": "Daily AI replies", "default_appointment": "Default appointment", "reminder_hours": "Reminder hours", "admin_notice": "Admin notice minutes", "asset_name": "Asset name", "when_to_use": "When to use", "image_file": "Image file", "upload_asset": "Upload asset", "delete": "Delete",
		"system_configuration": "System configuration", "integrations": "Integrations and environment", "integrations_copy": "WhatsApp, OpenRouter and Cloudflare settings. Existing secrets are never displayed.", "panel_preferences": "Panel preferences", "appearance": "Appearance", "language": "Language", "light": "Light", "dark": "Dark", "english": "English", "hebrew": "Hebrew", "whatsapp_cloud": "WhatsApp Cloud API", "openrouter": "OpenRouter", "cloudflare": "Cloudflare", "keep_secret": "Leave blank to keep the existing secret", "restart_required": "Integration changes are written to the environment file and take effect after the containers restart.", "save_system_settings": "Save system settings", "configured": "Configured", "not_configured": "Not configured",
		"customer_engagement": "Customer engagement", "ask_learn_reward": "Ask, learn and reward", "new_poll": "New poll", "new_questionnaire": "New questionnaire", "lottery": "Lottery", "campaign_history": "Campaign history", "results": "Results",
		"onboarding_welcome": "Welcome to OpenReception", "onboarding_welcome_copy": "Four short screens explain how to operate the receptionist, manage the business and connect required services.", "onboarding_dashboard": "Calendar and customers", "onboarding_dashboard_copy": "The main page shows the calendar, upcoming appointments, message activity and customer directory. Select an appointment to move it or update its status.", "onboarding_bot": "Bot settings", "onboarding_bot_copy": "Define the business name and type, services, prices, durations, hours, policies, reminders and visual assets. These fields are the assistant's source of truth.", "onboarding_system": "System settings", "onboarding_system_copy": "Connect WhatsApp Cloud API, OpenRouter and Cloudflare, select the model and panel language, then run readiness diagnostics. Existing secrets are never displayed again.", "onboarding_admin": "Manage through WhatsApp", "onboarding_admin_copy": "The admin number behaves like a customer until it sends Admin. After the PIN, the owner can manage appointments, Bot settings, customers and campaigns naturally for one hour.", "skip_tutorial": "Skip tutorial", "previous": "Previous", "next": "Next", "configure_bot": "Configure business", "configure_system": "Connect services",
	}
	if value := english[key]; value != "" {
		return value
	}
	return key
}
